version: '3.8'
services:
  backend:
    build: ../server
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
    ports:
      - "3000:3000"
    depends_on: []
  frontend:
    build: ../front
    ports:
      - "5173:5173"
  nginx:
    image: nginx:alpine
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend 